### ISSUE TITLE
你好，请问你的bootstrap在哪儿引用的

### ISSUE THREAD

**Issue by yuelinghunyu** [yanxiaojun617/webpack4-bootstrap4-demo#3]
你好，请问你的bootstrap在哪儿引用的

**Comment by yanxiaojun617** [comment]
https://stevenwestmoreland.com/2018/01/how-to-include-bootstrap-in-your-project-with-webpack.html

**Comment by yanxiaojun617** [comment]
1.安装依赖 npm install bootstrap jquery popper.js --save
https://github.com/yanxiaojun617/webpack4-bootstrap4-demo/blob/master/package.json

2.配置webpack rules —— scss 
npm install autoprefixer css-loader node-sass postcss-loader sass-loader style-loader --save-dev
https://github.com/yanxiaojun617/webpack4-bootstrap4-demo/blob/master/webpack.base.conf.js

3.导入Bootstrap
https://github.com/yanxiaojun617/webpack4-bootstrap4-demo/blob/master/src/assets/Common.js

**Comment by bzzx** [comment]
PS C:\txh\html\webpack4-bootstrap4-demo-master> npm run dev

> webpack4-bootstrap4-demo@1.0.0 dev C:\txh\html\webpack4-bootstrap4-demo-master
> cross-env NODE_ENV=dev webpack-dev-server --config webpack.config.js --progress

module.js:550
    throw err;
    ^

Error: Cannot find module 'locate-path'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\txh\html\webpack4-bootstrap4-demo-master\node_modules\_find-up@3.0.0@find-up\index.js:3:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack4-bootstrap4-demo@1.0.0 dev: `cross-env NODE_ENV=dev webpack-dev-server --config webpack.config.js --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack4-bootstrap4-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HUIPC\AppData\Roaming\npm-cache\_logs\2019-03-07T19_28_08_081Z-debug.log

**Comment by yanxiaojun617** [comment]
@bzzx npm i再试试
