### ISSUE TITLE
node10的版本无法install

### ISSUE THREAD

**Issue by bluekevin** [yanxiaojun617/webpack4-bootstrap4-demo#4]
提示 Maximum call stack size exceeded，降级？

**Comment by yanxiaojun617** [comment]
我确实没用node10跑过这个项目，一直使用8.9.4；所以用8.x版本肯定没问题；
你可以使用nvm安装/管理多个nodejs版本
https://www.jianshu.com/p/17d3249e0619

**Comment by yanxiaojun617** [comment]
我用nodev10.15.3没问题哦

**Comment by yanxiaojun617** [comment]
那你试一下？
