### ISSUE TITLE
npm run build之后 html引入js 和压缩后js不一致

### ISSUE THREAD

**Issue by jiyihui** [yanxiaojun617/webpack4-bootstrap4-demo#6]
![image](https://user-images.githubusercontent.com/26476858/61273182-830f3880-a7db-11e9-822b-f8ecaddf3097.png)

![image](https://user-images.githubusercontent.com/26476858/61273343-d5505980-a7db-11e9-9e98-1c0f2dcbbdc7.png)
如图 上图是打包之后的index.html 里面引入的js    第二张图是打包之后的js 列表，我本地node版本是  10.15.0 不知道是不是和node版本有关系

**Comment by jiyihui** [comment]
![image](https://user-images.githubusercontent.com/26476858/61281883-f7060c80-a7ec-11e9-97b8-b81f8ee93832.png)
我又试了 8.9.4版本，还是对不上hash值

**Comment by jiyihui** [comment]
![image](https://user-images.githubusercontent.com/26476858/61283579-f0c55f80-a7ef-11e9-9c5e-a4259c821579.png)

后来把webpack.base.conf.js 里面的  output的chuckhash改成 contenthash就解决了

**Comment by jiyihui** [comment]
我又试了下 不把 chunkhash改成contenthash也行，但是要加长度 
    output: {
        publicPath: isProd ? './' : '',
        path: path.resolve(__dirname, './dist'),
        filename: 'js/' + (isProd ? '[name].[chunkhash:8].min.js' : '[name].js'),
        chunkFilename: 'js/' + (isProd ? '[name].chunk.[chunkhash:10].min.js' : '[name].chunk.js'),
    },

**Comment by yanxiaojun617** [comment]
是的确实有这问题，感谢，改为chunkhash:8
